Repository Sitecore/developer-portal, pull requests merged in 2021-11, with the labels that each got.

#201 Fixed typos on ordercloud page
  data/data-navigation.ts
  data/markdown/pages/solution/commerce/product/ordercloud/index.md
  data/markdown/partials/solution/commerce/ordercloud.md
Labels: bug, documentation

#202 Jss trial updates
  data/markdown/pages/trials/jss-connected-demo/index.md
  data/markdown/partials/solution/content-management/jss.md
  data/markdown/partials/trials/jss-connected-demo/introduction.md
  pages/trials/[trial]/[parent]/[child].tsx
  pages/trials/[trial]/index.tsx
  scripts/static-paths.ts
Labels: enhancement

#199 Add promo on homepage for announcement
  data/promos/newpromo.ts
  pages/index.tsx
Labels: documentation

#205 Replacing promo content on homepage
  data/promos/newpromo.ts
Labels: documentation

#206 Security headers
  next.config.js
Labels: enhancement

#207 Added free Learning essentials course to Learn and product pages
  data/markdown/partials/learn/getting-started/composable-dxp.md
  data/markdown/partials/learn/getting-started/platform-dxp-development-frameworks.md
  data/markdown/partials/learn/getting-started/platform-dxp.md
  data/markdown/partials/learn/getting-started/product-features.md
  data/markdown/partials/solution/commerce/ordercloud.md
  data/markdown/partials/solution/commerce/sitecore-commerce.md
  data/markdown/partials/solution/content-management/jss.md
  data/markdown/partials/solution/content-management/sxa.md
  data/markdown/partials/solution/content-management/web-cms.md
  data/markdown/partials/solution/customer-data-management/cdp.md
  data/markdown/partials/solution/dam-and-content-operations/content-hub.md
  data/markdown/partials/solution/personalization-testing/personalize.md
Labels: documentation

#208 Adding SF Commerce connector to integrations list
  data/markdown/partials/learn/integrations/content-hub.md
  data/markdown/partials/solution/dam-and-content-operations/dam.md
Labels: documentation

#211 Added #cdp tag to the SSE configs for CDP/Personalize pages
  data/markdown/pages/solution/customer-data-management/index.md
  data/markdown/pages/solution/customer-data-management/product/cdp/index.md
  data/markdown/pages/solution/personalization-testing/index.md
  data/markdown/pages/solution/personalization-testing/product/personalize/index.md
Labels: documentation
