Repository Sitecore/developer-portal, pull requests merged in 2023-06, with the labels that each got.

#463 Added community articles for Edge
  apps/devportal/data/markdown/partials/solution/content-management/edge-xm.md
Labels: documentation

#475 Triggering Search Entity Click Event for external sources
  apps/devportal/src/components/integrations/sitecore-search/PreviewSearchInput.tsx
  apps/devportal/src/components/integrations/sitecore-search/SearchResults.tsx
Labels: search

#476 Bumped Search SDK version
  apps/devportal/package.json
  package-lock.json
Labels: search

#477 Bumped minor version of Search SDK
  apps/devportal/package.json
  package-lock.json
Labels: search

#492 Issue 491; set min-height for preview search
  apps/devportal/src/components/integrations/sitecore-search/PreviewSearchInput.tsx
  packages/tailwind-config/tailwind.config.js
Labels: bug
