Repository Sitecore/developer-portal, pull requests merged in 2024-02, with the labels that each got.

#633 Guided demos on product pages
  apps/devportal/data/markdown/pages/content-management/content-hub-one.md
  apps/devportal/data/markdown/pages/content-management/search.md
  apps/devportal/data/markdown/pages/content-management/xm-cloud.md
  apps/devportal/data/markdown/pages/customer-data-management/cdp.md
  apps/devportal/data/markdown/pages/dam-and-content-operations/content-hub.md
  apps/devportal/data/markdown/pages/dam-and-content-operations/dam.md
  apps/devportal/data/markdown/pages/integrations/connect.md
  apps/devportal/data/markdown/pages/marketing-automation/send.md
  apps/devportal/data/markdown/pages/personalization-testing/personalize.md
  apps/devportal/src/layouts/DefaultContentPage.tsx
  apps/devportal/src/lib/interfaces/page-info.ts
  apps/devportal/src/lib/theme/components/cardTheme.ts
  apps/devportal/src/lib/theme/components/modalTheme.ts
  apps/devportal/src/lib/theme/theme.ts
  packages/ui/components/common/GuidedDemo.tsx
  packages/ui/components/common/Hero.tsx
Labels: enhancement

#641 Fixed issue where search facets didnt work when upgrading to sdk v2.2.2
  apps/devportal/package.json
  apps/devportal/src/components/sitecore-search/SearchFacets.tsx
  package-lock.json
Labels: bug, search

#635 Adding clarity around XP style component personalization and XMC personalization
  apps/devportal/data/markdown/pages/learn/faq/xm-cloud-embedded-personalization/feature-matrix.md
Labels: documentation
